; PlatformIO Project Configuration File
;
;   ESP32-S2 Mini (Lolin S2 Mini) + LCD ST7789 76x284
;   Driver: TFT_eSPI configurada via build_flags
;
; https://docs.platformio.org/page/projectconf.html

[env:lolin_s2_mini]
platform = espressif32@6.6.0
board = lolin_s2_mini
framework = arduino
monitor_speed = 115200
upload_port = COM7
monitor_port = COM7
board_build.partitions = huge_app.csv
lib_deps =
	bodmer/TFT_eSPI
	mathertel/Radio
build_flags =
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D USER_SETUP_LOADED
	-D ST7789_DRIVER
	; --- CALIBRACAO: usar RAM completa do controlador (240 x 320) ---
	; (depois de achar o offset volta-se a 76 x 284)
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
	; --- Pinagem ---
	-D TFT_MISO=40
	-D TFT_MOSI=35
	-D TFT_SCLK=36
	-D TFT_CS=34
	-D TFT_DC=37
	-D TFT_RST=38
	-D TOUCH_CS=-1
	; --- Fontes ---
	-D LOAD_GLCD=1
	-D LOAD_FONT2
	-D LOAD_FONT4
	-D LOAD_FONT6
	-D LOAD_FONT7
	-D LOAD_GFXFF
	-D SMOOTH_FONT
	; --- Cor / SPI ---
	-D TFT_RGB_ORDER=TFT_BGR
	-D SPI_FREQUENCY=80000000
	-I include
